### ISSUE TITLE
Use json as input parameter instead of cbor

### ISSUE THREAD

**Issue by cryptoAtwill** [adlrocha/hc-subnet-actor#13]
For input parameters, we can use json instead of cbor. JSON would be easier to invoke, at the same time, it is easier to implement when we have cross language invocation.

**Comment by sergefdrv** [comment]
AFAIK, it is important to keep the message size as small as possible, therefore it is a de-facto standard to use CBOR serialization with tuple encoding.

**Comment by adlrocha** [comment]
Closing because it is already fixed (and settled). We are using CBOR.

**Comment by cryptoAtwill** [comment]
Where I'm coming from is for those complex data structures, like checkpoint, we can use json to send to client then client to actor is still cbor. That way is easier to use for client users.
